export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";